[phases.setup]
nixPkgs = ["imagemagick", "tesseract"]

[phases.install]
dependsOn = ["setup"]

[variables]
NIXPACKS_METADATA = "pdf-knowledge-system"
MAGICK_CONFIGURE_PATH = "/nix/store"
TESSDATA_PREFIX = "/app" 