# Simplified nixpacks config for fast deployment
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --only=production && npm cache clean --force"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node scripts/migrate-production.js && node server.js"
onHealthcheckFail = "restart"

[variables]
NODE_ENV = "production"
PORT = "8080" 