[build]
  # Explicitly disable Dockerfile and use Nixpacks
  builder = "NIXPACKS"
  buildCommand = "npm ci"
  dockerfilePath = "DISABLED"

[deploy]
  startCommand = "node scripts/migrate-production.js && node server.js"
  healthcheckEnabled = true
  healthcheckPath = "/simple-health"
  healthcheckTimeout = 120

[env]
  NODE_ENV = "production"
  PORT = "8080"
  SSL_ENABLED = "true"
  SSL_REJECT_UNAUTHORIZED = "true"
  # Increase timeouts for API and uploads
  API_TIMEOUT_MINUTES = "15"
  UPLOAD_TIMEOUT_MINUTES = "30" 