[build]
  builder = "dockerfile"
  # Không cần buildCommand khi sử dụng Dockerfile

[deploy]
  startCommand = "node scripts/migrate-production.js && node server.js"
  # Disable health check completely
  healthcheckEnabled = false
  # healthcheckPath = "/"
  # healthcheckTimeout = 60

[env]
  NODE_ENV = "production"
  PORT = "8080"
  SSL_ENABLED = "true"
  SSL_REJECT_UNAUTHORIZED = "true" 