[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "node scripts/migrate-production.js && npm start"
  # Disable health check completely
  healthcheckEnabled = false
  # healthcheckPath = "/"
  # healthcheckTimeout = 60

[env]
  NODE_ENV = "production"
  PORT = "8080"
  SSL_ENABLED = "true"
  SSL_REJECT_UNAUTHORIZED = "true" 