[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm run railway:start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"
  PORT = "8080"
  SSL_ENABLED = "true"
  SSL_REJECT_UNAUTHORIZED = "true"
  UPLOAD_TIMEOUT_MINUTES = "30"
  API_TIMEOUT_MINUTES = "15"
  MAX_FILE_SIZE = "150mb"
  MAX_PDF_PAGES = "100"

[resources]
  memoryGB = 3
  vCPU = 1 